# 의존성 설치 단계
FROM node:18-alpine AS deps
WORKDIR /app
COPY package.json yarn.lock* package-lock.json* ./
RUN npm ci --omit=dev && npm cache clean --force

# 빌드 단계
FROM node:18-alpine AS builds
WORKDIR /app
COPY --from=deps /app/node-modules ./node-modules
COPY . .
ENV NEXTJS_TELEMETRY_DISABLED=1
RUN npm run build

#실행 단계
FROM node:18-alpine AS runner
WORKDIR /app

RUN addgroup -g 1001 -S nodejs
RUN adduser -S nextjs -u 1001

# 굳이 얘는 꺼내고
COPY --from=builds --chown=nextjs:nodejs /app/.next/standalone ./
# 굳이 얘는 안꺼내고 넣음 standalone이 실행파일이라는거같음 
COPY --from=builds --chown=nextjs:nodejs /app/.next/static ./.next/static
COPY --from=builder /app/public ./public

USER nextjs
EXPOSE 3000
CMD ["node", "server.js"]