import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Navbar from "../component/navbar/Navbar";
import * as style from './layout.css';

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "한자 한 자",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body style={{ margin: 0 }}>
        <Navbar />
        <div className={style.container}>
          {children}
        </div>
      </body>
    </html>
  );
}