'use client'
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import localFont from 'next/font/local';
import Navbar from "../component/Navbar/Navbar";
import Sidebar from "../component/Sidebar/Sidebar"
import {container} from './layout.css.ts';
import { useEffect, useState } from 'react';
import ClientWrapper from "@/component/ClientWrapper/ClientWrapper.tsx";

const inter = Inter({ subsets: ["latin"] });

const pretendard = localFont({
  src: "../assets/fonts/Pretendard-Regular.woff",
  display: "swap",
  weight: "45 920",
});

async function generateMetadata() {
  return {
    title: "한자 한 자",
    description: "Generated by create next app",
  }
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const [isLoggedIn, setIsLoggedIn] = useState<boolean> (false)
  useEffect

  return (
    <html lang="en">
      <body style={{ margin: 0 }}>
        <div className={`${pretendard.className} ${container}`}>
        {/* <div className={`${pretendard.className}`}> */}
          {/* {children} */}

          <ClientWrapper>
          {children}
          </ClientWrapper>
        </div>
      </body>
    </html>
  );
}