import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import Navbar from './navbar.tsx'
import './globals.css'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (

    <html lang="en">
      <head>

      </head>
      <body className={inter.className} style={{ height : ''}}>
        <Navbar />

        {children}


        </body>
    </html>
  )
}
